tasks:
  - init: |
      poetry update
      docker-compose pull
  - command: docker-compose up


ports:
  - port: 80
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
