tasks:
  - init: |
      echo "VITE_BASE_API_URL=$(gp url 80)" > zql_ui/.env.development
      poetry install
      docker-compose pull
  - command: docker-compose up


ports:
  - port: 80
    onOpen: ignore
    visibility: public
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
