services:
  api:
    build: .
    container_name: zql_api
    ports:
      - 80:80
    volumes:
      - .:/code

  ui:
    build: zql_ui/.
    container_name: zql_ui
    ports:
      - 3000:3000
    volumes:
      - ./zql_ui/src:/app/src
    command: npm run dev
